branches:
  only:
    - master
sudo: required
services:
  - docker
language: python
script:
  - ./scripts/docker-build-and-test.sh
deploy:
  provider: script
  script: ./scripts/docker-build-and-deploy.sh
  on:
    branch: master
after_success:
  - pip install coveralls
  - coveralls
