branches:
  only:
    - master
sudo: required
services:
  - docker
script:
  - docker build -t vanillaslice/dawdle-test -f ./docker/test.Dockerfile .
  - docker run vanillaslice/dawdle-test /opt/app/scripts/lint.sh
  - docker run vanillaslice/dawdle-test /opt/app/scripts/test.sh
deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
after_success:
  - coveralls
