language: python
python: 3.7
dist: xenial
branches:
  only:
    - master
    - develop
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - ./scripts/lint.sh
  - ./scripts/test.sh
after_success:
  - coveralls
