branches:
  only:
    - master
sudo: required
services:
  - docker
language: python
python:
  - 3.8
script:
  - ./scripts/ci/test.sh
deploy:
  provider: script
  script: ./scripts/ci/deploy.sh
  on:
    branch: master
after_success:
  - ./scripts/ci/coverage.sh
