branches:
  only:
    - master
sudo: required
services:
  - docker
script:
  - if [[ $TRAVIS_PULL_REQUEST != 'false' ]]; then ./scripts/build-and-test.sh; fi
deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
after_success:
  - coveralls
