coverage:
  status:
    project:
      default:
        target: auto
      back-end:
        target: auto
        flags:
          - back-end
flags:
  back-end:
    paths:
      - back-end
    carryforward: true
