version: '3'
services:
  mongodb:
    image: mongo:4.0.9-xenial
    volumes:
      - ./mongodb/docker-entrypoint-initdb.d/local-user.js:/docker-entrypoint-initdb.d/local-user.js
      - ./mongodb/data/db:/data/db
  dawdle:
    build:
      context: .
      dockerfile: ./docker/local.Dockerfile
    ports:
      - 5000:8000
    environment:
      - DEBUG=True
      - ENV=local
      - MONGODB_HOST=mongodb
      - MONGODB_PASSWORD=local-user-password
      - MONGODB_USERNAME=local-user
    volumes:
      - ./dawdle:/opt/app/dawdle
      - ./config.py:/opt/app/config.py
      - ./run.py:/opt/app/run.py
