version: '3'
services:
  mongodb:
    image: mongo:4.1.9-xenial
    volumes:
      - ./docker/mongodb/setup.js:/docker-entrypoint-initdb.d/setup.js
      - ./docker/mongodb/data:/data/db
  dawdle-api:
    build:
      context: .
      dockerfile: ./docker/local.Dockerfile
    ports:
      - 5000:8000
    environment:
      - MONGODB_HOST=mongodb://dawdle:dawdle@mongodb:27017/dawdle
      - SERVER_NAME=127.0.0.1:5000
      - SESSION_COOKIE_DOMAIN=127.0.0.1:5000
    volumes:
      - ./dawdle:/opt/app/dawdle
      - ./config.py:/opt/app/config.py
      - ./run.py:/opt/app/run.py
      - ./instance:/opt/app/instance
      - ./docs/api.yml:/opt/app/docs/api.yml
