name: Build
on:
  push:
    branches:
      - master
    ignore-paths:
      - 'api/**'
  pull_request:
    branches:
      - master
    ignore-paths:
      - 'api/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
