name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Test Image
        run: |
          docker build -t vanillaslice/dawdle-test -f ./docker/test.Dockerfile .
      - name: Test
        run: |
          docker run vanillaslice/dawdle-test
