name: Deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'back-end/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Deploy
        if: steps.wait-for-build.outputs.conclusion == 'success'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker login --username=_ --password="$HEROKU_API_KEY" registry.heroku.com
          docker build -t registry.heroku.com/dawdle/web -f ./docker/prod.Dockerfile .
          docker push registry.heroku.com/dawdle/web
          image_id=$(docker inspect registry.heroku.com/dawdle/web --format={{.Id}})
          payload='{"updates":[{"type":"web","docker_image":"'"$image_id"'"}]}'
          curl -n -X PATCH https://api.heroku.com/apps/dawdle/formation \
              -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
              -H "Authorization: Bearer $HEROKU_API_KEY" \
              -H "Content-Type: application/json" \
              -d "$payload"
