name: Deploy API
on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
jobs:
  build:
    if: "!startsWith(github.event.commits[0].message, 'release: v')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Tests
        run: ./api/scripts/ci/tests.sh
      - name: Collect Coverage
        run: ./api/scripts/ci/coverage.sh
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./api/coverage.xml
          flags: api
          fail_ci_if_error: true
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: ./api/scripts/ci/deploy.sh
