name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    if: "startsWith(github.event.commits[0].message, 'release: v')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait for deploy to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-deploy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: deploy
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Get version
        id: vars
        run: echo ::set-output name=version::$(cat version.txt)
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          release_name: ${{ steps.vars.outputs.version }}
