name: Release
on:
  push:
    branches:
      - master
jobs:
  buildOld:
    if: "startsWith(github.event.commits[0].message, 'release: v')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Test
        run: |
          docker build -t vanillaslice/dawdle-test -f ./docker/test.Dockerfile .
          docker run vanillaslice/dawdle-test
          docker cp $(docker ps -l -q):/opt/app/.coverage .coverage.tmp
      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          pip install coveralls
          coverage combine
          coveralls
  deployOld:
    needs: [buildOld]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker login --username=_ --password="$HEROKU_API_KEY" registry.heroku.com
          docker build -t registry.heroku.com/dawdle/web -f ./docker/prod.Dockerfile .
          docker push registry.heroku.com/dawdle/web
          image_id=$(docker inspect registry.heroku.com/dawdle/web --format={{.Id}})
          payload='{"updates":[{"type":"web","docker_image":"'"$image_id"'"}]}'
          curl -n -X PATCH https://api.heroku.com/apps/dawdle/formation \
              -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
              -H "Authorization: Bearer $HEROKU_API_KEY" \
              -H "Content-Type: application/json" \
              -d "$payload"
  buildApi:
    if: "startsWith(github.event.commits[0].message, 'release: v')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Tests
        run: ./api/scripts/ci/tests.sh
      - name: Collect Coverage
        run: ./api/scripts/ci/coverage.sh
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./api/coverage.xml
          flags: api
          fail_ci_if_error: true
  deployApi:
    needs: [buildApi]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: ./api/scripts/ci/deploy.sh
